name: Nix Formatting

on:
  push:
    branches:
      - main  # Adjust this branch name if necessary

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Nix
        run: curl -L https://nixos.org/nix/install | sh

      - name: Install nixfmt
        run: nix-env -iA nixpkgs.nixUnstable

      - name: Format .nix files
        run: nixfmt $(git ls-files '*.nix')
