name: "Format Nix files"
on:
  pull_request:
  push:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      run: curl -L https://nixos.org/nix/install | sh
      # Note: The above command will install Nix, you can also use nix action for more control over Nix installation.

    - name: Run nixfmt
      run: nix-shell -p nixpkgs.nixfmt --run "nixfmt --recursive"
