name: "Format Nix files"
on:
  pull_request:
  push:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install nixfmt
      run: nix-env -iA nixpkgs.nixfmt

    - name: Run nixfmt
      run: nixfmt --recursive
