name: "Format Nix files"
on:
  pull_request:
  push:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      run: curl -L https://nixos.org/nix/install | sh

    - name: Set up Nix
      run: echo ". /home/runner/.nix-profile/etc/profile.d/nix.sh" >> $GITHUB_ENV

    - name: Run nixfmt
      run: nix-env -iA nixpkgs.nixfmt --file '<nixpkgs>'
          && $HOME/.nix-profile/bin/nixfmt --recursive
