name: "Format Nix files"
on:
  pull_request:
  push:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install and format with nixfmt
      run: |
        curl -L https://nixos.org/nix/install | sh
        nix-shell -p nixpkgs.nixfmt --run "nixfmt --recursive"
